version: "3"

services:
  react-cra-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    tty: true
    stdin_open: false
    container_name: react-cra-container

  react-cra-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["yarn", "test"]
    tty: true
    stdin_open: true
    container_name: react-cra-test-container

  react-prod-nginx:
    image: readyp/prod-react-cra
    ports:
      - 80:80
